"""Helpers for `recto migrate-from-nssm`. Extracted from recto.cli.

These functions are pure (no I/O, no side effects) and small. They
live in their own module so cli.py stays under the Cowork Write-tool
size threshold while still being a thin dispatcher rather than a
1000-line god-module. Same pattern as ``recto._launcher_run`` --
private (underscore-prefix) module, re-imported by name from
``recto.cli``.

If you're reading this in v0.3+: feel free to inline these back into
cli.py once the Cowork sandbox is no longer the operator's primary
authoring environment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from recto.nssm import NssmConfig

__all__ = [
    "build_migration_plan",
    "escape_yaml",
    "generate_service_yaml",
]


def build_migration_plan(
    *,
    nssm_cfg: NssmConfig,
    secrets: list[tuple[str, str]],
    yaml_out: Path,
    python_exe: str,
) -> dict[str, Any]:
    """Build a dict describing what migrate-from-nssm WOULD do.

    Secret VALUES are masked (replaced with '<redacted>') so the plan
    can be JSON-printed without leaking. Operator should review the
    plan with --dry-run before applying.
    """
    return {
        "service": nssm_cfg.service,
        "current_app_path": nssm_cfg.app_path,
        "current_app_parameters": nssm_cfg.app_parameters,
        "current_app_directory": nssm_cfg.app_directory,
        "current_environment_extra_count": len(secrets),
        "secrets_to_install": [
            {"name": k, "value": "<redacted>"} for k, _ in secrets
        ],
        "yaml_out": str(yaml_out),
        "new_app_path": python_exe,
        "new_app_parameters": f"-m recto launch {yaml_out}",
    }


def generate_service_yaml(
    *,
    service: str,
    nssm_cfg: NssmConfig,
    secret_keys: list[str],
) -> str:
    """Produce the generated service.yaml text.

    Hand-rolled (not via PyYAML's dump) so we control formatting:
    fields appear in a stable order, comments are preserved, and the
    output is human-reviewable. PyYAML's default style would munge
    quoting on values with `:` or `#` and lose readability.
    """
    lines: list[str] = []
    a = lines.append
    a("# Generated by `recto migrate-from-nssm`.")
    a(f"# Source NSSM service: {nssm_cfg.service}")
    a("# Review and edit before relying on this in production.")
    a("apiVersion: recto/v1")
    a("kind: Service")
    a("metadata:")
    a(f"  name: {service}")
    if nssm_cfg.display_name:
        a(f"  description: \"{escape_yaml(nssm_cfg.display_name)}\"")
    a("spec:")
    a(f"  exec: \"{escape_yaml(nssm_cfg.app_path)}\"")
    if nssm_cfg.app_parameters:
        a("  args:")
        for w in nssm_cfg.app_parameters.split():
            a(f"    - \"{escape_yaml(w)}\"")
    if nssm_cfg.app_directory:
        a(f"  working_dir: \"{escape_yaml(nssm_cfg.app_directory)}\"")
    if secret_keys:
        a("  secrets:")
        for key in secret_keys:
            a(f"    - name: {key}")
            a("      source: credman")
            a(f"      target_env: {key}")
            a("      required: true")
    a("  restart:")
    a("    policy: always")
    a("    backoff: exponential")
    a("    initial_delay_seconds: 1")
    a("    max_delay_seconds: 60")
    a("    max_attempts: 10")
    a("")
    return "\n".join(lines)


def escape_yaml(s: str) -> str:
    """Escape backslashes and double-quotes for YAML double-quoted strings."""
    return s.replace("\\", "\\\\").replace("\"", "\\\"")
